# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [1]:
# Write your code below.

%load_ext dotenv
%dotenv

In [2]:
import dask.dataframe as dd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [8]:
import os
from glob import glob

# Write your code below. 
#LOAD
PRICE_DATA = os.getenv("PRICE_DATA")

parquet_files = glob(
    os.path.join(PRICE_DATA, "**/*.parquet"),
    recursive=True
)

parquet_files[:5]

['../../05_src/data/prices\\ACN\\ACN_2001\\part.0.parquet',
 '../../05_src/data/prices\\ACN\\ACN_2001\\part.1.parquet',
 '../../05_src/data/prices\\ACN\\ACN_2002\\part.0.parquet',
 '../../05_src/data/prices\\ACN\\ACN_2002\\part.1.parquet',
 '../../05_src/data/prices\\ACN\\ACN_2003\\part.0.parquet']

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [9]:
import pandas as pd #import pandas

dd_a1= dd.read_parquet(parquet_files).set_index("ticker") #read parquet files
dd_a1

# assign lags for Close and Adj Close
dd_p1 = (
    dd_a1
    .groupby('ticker', group_keys = False)
    .apply(
        lambda x: x.sort_values('Date', ascending = True)
            .assign(
                Close_lag_1 = x['Close'].shift(1),
                Adj_Close_lag_1 = x['Adj Close'].shift(1)),
         meta = pd.DataFrame(data = {'Date': 'datetime64[ns]',
                    'Open': 'f8',
                    'High': 'f8',
                    'Low': 'f8',
                    'Close': 'f8',
                    'Adj Close': 'f8',
                    'Volume': 'i8',
                    'source': 'object',
                    'Year': 'int32',
                    'Close_lag_1': 'f8',
                    'Adj_Close_lag_1': 'f8'},
                    index = pd.Index([], dtype=pd.StringDtype(), name='ticker'))
        ))

# Calculate returns
dd_p2 = dd_p1.assign(
    returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)
# Calculate hi_low_range 
dd_feat = dd_p2.assign(
    hi_low_range = lambda x: x['High'] - x['Low']
)
#check dask dataframe 
dd_feat

Dask DataFrame Structure:
                  Date    Open    High     Low   Close Adj Close  Volume  source    Year Close_lag_1 Adj_Close_lag_1 returns hi_low_range
npartitions=60
ACN             object  object  object  object  object    object  object  object  object      object          object  object       object
ALDX               ...     ...     ...     ...     ...       ...     ...     ...     ...         ...             ...     ...          ...
...                ...     ...     ...     ...     ...       ...     ...     ...     ...         ...             ...     ...          ...
ZIXI               ...     ...     ...     ...     ...       ...     ...     ...     ...         ...             ...     ...          ...
ZIXI               ...     ...     ...     ...     ...       ...     ...     ...     ...         ...             ...     ...          ...
Dask Name: assign, 14 expressions
Expr=Assign(frame=Assign(frame=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(bf63007), _other='ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x0000017FE7D65B20>, args=(), kwargs={})))))

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [ ]:
# Write your code below.
dd_feat.compute()

#rolling mean of returns for 10 days.  Assumption: calculation up to 10 days of data available. If it has less than 10 days, calculate mean for available days.

dd_final = (
    dd_feat
    .groupby('ticker', group_keys = False)
    .apply(
        lambda x: x.sort_values('Date', ascending = True)
            .assign
            (rolling_mean = x['returns'].rolling(window=10, min_periods=1).mean()),
    meta = dd_feat._meta.assign(rolling_mean = 'f8')
))
dd_final.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Adj_Close_lag_1,returns,hi_low_range,rolling_mean
ticker,,,,,,,,,,,,,,
ACN,2001-07-19,15.10,15.29,15.00,15.17,11.404394,34994300.0,ACN.csv,2001,NaN,NaN,NaN,0.29,NaN
ACN,2001-07-20,15.05,15.05,14.80,15.01,11.284108,9238500.0,ACN.csv,2001,153.839996,148.655960,-0.902431,0.25,-0.902431
ACN,2001-07-23,15.00,15.01,14.55,15.00,11.276587,7501000.0,ACN.csv,2001,154.550003,149.342056,-0.902944,0.46,-0.902688
ACN,2001-07-24,14.95,14.97,14.70,14.86,11.171341,3537300.0,ACN.csv,2001,156.380005,151.110382,-0.904975,0.27,-0.903450
ACN,2001-07-25,14.70,14.95,14.65,14.95,11.238999,4208100.0,ACN.csv,2001,157.669998,152.356918,-0.905182,0.30,-0.903883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZIXI,2020-03-26,4.06,4.53,3.88,4.51,4.510000,1668500.0,ZIXI.csv,2020,4.040000,4.040000,0.116337,0.65,-0.105798
ZIXI,2020-03-27,4.49,4.71,4.10,4.60,4.600000,1146800.0,ZIXI.csv,2020,4.000000,4.000000,0.150000,0.61,-0.100798
ZIXI,2020-03-30,4.83,4.87,4.44,4.64,4.640000,1212000.0,ZIXI.csv,2020,3.850000,3.850000,0.205195,0.43,-0.078200
ZIXI,2020-03-31,4.60,4.69,4.10,4.31,4.310000,1057200.0,ZIXI.csv,2020,3.770000,3.770000,0.143236,0.59,-0.053170
ZIXI,2020-04-01,4.11,4.16,3.80,3.82,3.820000,539500.0,ZIXI.csv,2020,3.780000,3.780000,0.010582,0.36,-0.019446

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?
+ Would it have been better to do it in Dask? Why?

(1 pt)

1. No, converting to pandas wasn’t required- Dask can handle it

2. Using Dask is better for large datasets because it computes in parallel and avoids loading everything into memory.

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.